# Generated by Django 2.2 on 2020-08-23 13:59

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Powtoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='content')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powtoon_owner', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('shared_with', models.ManyToManyField(blank=True, null=True, related_name='powtoon_shared_with', to=settings.AUTH_USER_MODEL, verbose_name='shared_with')),
            ],
            options={
                'verbose_name': 'Powtoon',
                'verbose_name_plural': 'Powtoons',
            },
        ),
    ]
