# Generated by Django 2.2 on 2020-08-25 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powtoons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powtoon',
            name='shared_with',
            field=models.ManyToManyField(related_name='powtoon_shared_with', to=settings.AUTH_USER_MODEL, verbose_name='shared_with'),
        ),
    ]
